### ISSUE TITLE
why not output cursor

### ISSUE THREAD

**Issue by snowman** [sindresorhus/restore-cursor#3]
i don't know what exactly i'm talking about here...

**Comment by sindresorhus** [comment]
I don't understand the question. Can you elaborate?

**Comment by snowman** [comment]
```
The escape sequence \x1BE, or Esc+E, is NEL or "Next line", 
and is used on older terminals and mainframes to denote CR+LF, or \r\n.
```
https://stackoverflow.com/questions/15011478/ansi-questions-x1b25h-and-x1be

https://en.wikipedia.org/wiki/ANSI_escape_code
CSI ? 25 h	DECTCEM Shows the cursor, from the VT320.
